Bugfix/schema db
nsdonato/back-invoices pull request #11
Opened 2023-01-19 17:16 UTC by jpaddeo

# 🧾 Invoices App Pull Request

## Descripcion ✏️

Conforme al update del issue #4 y que @rretta me pasó los datos de conexión a la BD ajusté el data.json con ids "productivos" (ya en BD) y ajusté script de seed (`prisma/seed.ts`) para poder ejecutarlo varias veces y que no falle (y lo puedan probar).

## Como testear? 🐛

Dentro de la carpeta raíz (dónde está el package.json). Ejecutar los siguientes comandos:

```

npm run prisma generate

npm run prisma:seed

```

2023-01-19 19:38 UTC, nsdonato approved these changes

2023-01-19 19:48 UTC, phreakphreak commented
actualizar la descripcion del pull request

npm run prisma:generate

2023-01-19 20:16 UTC, phreakphreak requested changes

2023-01-19 20:16 UTC, phreakphreak commented on prisma/seed.ts
> +    await prisma.invoice.upsert({
el metodo upsert puede generar un tipo de operacion invalid con prisma al no ser una transaction aqui un ejemplo del error [issue prisma con upsert](https://github.com/prisma/prisma/issues/11038)

aqui  te aporto con algo de de codigo para probar el seed en la base de datos

```suggestion
    await prisma.$transaction(
    data.map((d: Data) =>
      prisma.invoice.upsert({
        where: { id: d.id },
        update: {},
        create: {
          paymentDue: new Date(d.paymentDue),
          description: d.description,
          status: d.status,
          paymentTerms: d.paymentTerms,
          total: d.total,
          address: {
            create: {
              street: d.senderAddress.street,
              city: d.senderAddress.city,
              postCode: d.senderAddress.postCode,
              country: d.senderAddress.country,
            },
          },
          client: {
            create: {
              name: d.clientName,
              email: d.clientEmail,
              address: {
                create: {
                  street: d.clientAddress.street,
                  city: d.clientAddress.city,
                  postCode: d.clientAddress.postCode,
                  country: d.clientAddress.country,
                },
              },
            },
          },
          items: {
            create: [...d.items],
          },
        },
      })
    )
  );
```

2023-01-19 20:22 UTC, phreakphreak commented on prisma/seed.ts
>    data.forEach(async (d: Data) => {
aqui  te aporto con algo de de codigo para probar el seed en la base de datos

```suggestion
    await prisma.$transaction(
    data.map((d: Data) =>
      prisma.invoice.upsert({
        where: { id: d.id },
        update: {},
        create:{
        // .... 
        }
      })
    )
  );
```

2023-01-20 01:54 UTC, jpaddeo commented on prisma/seed.ts
> +    await prisma.invoice.upsert({
Buen dato!

2023-01-20 02:18 UTC, jpaddeo commented
> Revisando un poco, me di cuenta que al hacer un cambio en el repositorio con la estructura del proyecto. Se debe mover el archivo `prisma/seed.ts` a `bin/seed.ts` sin ese cambio la branch no se podrá hacer merge.

@Jean-Dv con este comentario tengo diferencias toda vez que la recomendación de prisma es mantener los scripts de seed dentro de la carpeta `prisma`:

![image](https://user-images.githubusercontent.com/3083587/213603780-c55ddc1d-5474-4894-81ee-1feba5e4f105.png)

Lo que si se podría pensar es crear una carpeta seeders dentro de la misma como para ordenar futuros nuevos seeders.

2023-01-20 02:20 UTC, jpaddeo commented on prisma/seed.ts
>    data.forEach(async (d: Data) => {
Aplicados los cambios sugeridos en commit [a66a9a168e287f2518ae5b2422c529c3607f51f1](https://github.com/nsdonato/back-invoices/pull/11/commits/a66a9a168e287f2518ae5b2422c529c3607f51f1)

2023-01-20 03:20 UTC, phreakphreak approved these changes

2023-01-20 03:21 UTC, phreakphreak commented
concuerdo con @jpaddeo que lo correspondiente a prisma se conserve en su directorio

2023-01-20 14:45 UTC, merged