Feature/task 5
nsdonato/back-invoices pull request #14
Opened 2023-01-23 01:12 UTC by Jean-Dv

# 🧾 Invoices App Pull Request

## Descripcion ✏️

Aquí están las configuraciones y test para las siguentes rutas:
- ``` /api/v1/invoices ```
- ```/api/v1/invoices/:id```

## Como testear? 🐛

No hay mucha ciencia, solo tienes que colocar
``` npm run test ``` o puedes iniciar el servicio con ```npm run dev``` entrar a las rutas anteriormente mencionadas con petición ```GET```

2023-01-23 20:05 UTC, nsdonato requested changes

2023-01-23 20:05 UTC, nsdonato commented on src/server.ts
>  // Routes
Eliminemos los comentarios innecesarios.

2023-01-23 20:05 UTC, nsdonato commented on src/server.ts
> +import errorHandler from '@middlewares/error-handler'
Podríamos cambiar esto para mantener los nombres, ya que dice lo mismo que la función exportada pero alrevés 

```suggestion
import errorHandler from '@middlewares/error-handler'
import handleError from '@middlewares/error-handler'
```

2023-01-25 10:56 UTC, nsdonato approved these changes

2023-01-27 02:00 UTC, AllegriM approved these changes

2023-01-27 09:12 UTC, merged